### PR TITLE
Some additional edits

### PR DESCRIPTION
**Pull request by PaulSchulz**
Minor updates fro readability.

### CODE REVIEW

**Comment by ToshioCP** [comment]
Hi, Paul.
Thank you for the pull requests.
They have been merged.
You helped me a lot.
Thank you again.

By the way, if you have ruby, the source files can be compiled by rake command.
$ rake
Then src/secXX.src.md will be compiled to gfm/secXX.md so that it can be seen on GITHUB.
For further information, see [How to build Gtk4 Tutorial](https://github.com/ToshioCP/Gtk4-tutorial/pull/18).

Toshio

**Comment by PaulSchulz** [comment]
Hi Toshio,

Thank you for your email.

Could you sent the link again for building the tutorial?

Cheers,
Paul

**Comment by ToshioCP** [comment]
Dear Paul,

The address is:
https://github.com/ToshioCP/Gtk4-tutorial/blob/main/gfm/Readme_for_developers.md

The link is also included in the "readme.md". 

Toshio

**Comment by PaulSchulz** [comment]
Cheers, it looks like I already had it installed :-)

Thanks for this. I like the generated 'diff's in the documentation.

Regards,
Paul

**Pull request merged**
